// 迁移至 @qcqx/lattice-foundation — 此文件保留为 re-export 桥接
export {
  getDefaultGlobalConfig,
  getDefaultLocalConfig,
  readGlobalConfig,
  writeGlobalConfig,
  readLocalConfig,
  writeLocalConfig,
  readResolvedConfig,
  readExplicitEmbeddingConfig,
  getUsername,
  isInitialized,
  hashPassword,
  verifyPassword,
  generateJwtSecret,
  readWebAuth,
  writeWebAuth,
  clearWebAuth,
  isAuthEnabled,
} from '@qcqx/lattice-foundation';
